# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: projets-sig@makina-corpus.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moodwalkr.fr" # the base hostname & protocol for your site
analytics: UA-40919875-1

translate_meta:
  en:
    title: MoodWalkR
    description: The application to calculate thematic routes for pedestrians
    keywords: MoodWalkR, museum, nightlife, calm, nature, walking
  fr:
    title: MoodWalkR
    description: L'application permettant de calculer des itinéraires thématiques à destination des piétons
    keywords: MoodWalkR, musée, vie nocturne, calme, nature, ballade, promenade
  es:
    title: MoodWalkR
    description: L'application permettant de calculer des itinéraires thématiques à destination des piétons
    keywords: MoodWalkR, musée, vie nocturne, calme, nature, ballade, promenade

# Build settings
markdown: kramdown
future: true
sass:
    sass_dir: jekyll-assets/css/
    style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts-en" # previously `post` in Jekyll 2.2.
    values:
      layout: "default-en"

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts-es" # previously `post` in Jekyll 2.2.
    values:
      layout: "default-es"

translate_menu:
  en:
    home:
      name: "Home"
      url: "/en/about/index.html"
    product:
      name: "Product"
      url: "/en/about/product.html"
    references:
      name: "References"
      url: "/en/about/references.html"
    contact:
      name: "Contact"
      url: "/en/about/contact.html"

  fr:
    home:
      name: "Accueil"
      url: "/fr/apropos/index.html"
    product:
      name: "Produit"
      url: "/fr/apropos/produit.html"
    references:
      name: "Références"
      url: "/fr/apropos/references.html"
    contact:
      name: "Contact"
      url: "/fr/apropos/contact.html"

  es:
    home:
      name: "Inicio"
      url: "/es/acerca-de/index.html"
    product:
      name: "Producto"
      url: "/es/acerca-de/produit.html"
    references:
      name: "Referencias"
      url: "/es/acerca-de/references.html"
    contact:
      name: "Contacto"
      url: "/es/acerca-de/contact.html"
